---
# h/t to http://stackoverflow.com/a/21494483/1676099
- name: add SAN to openssl conf file
  become: yes
  ini_file:
      dest: /etc/ssl/openssl.cnf
      section: '{{ item.section }}'
      option: '{{ item.option }}'
      value: '{{ item.value }}'
  with_items:
      - section: v3_ca
        option: subjectAltName
        value: '@alternate_names'
      - section: v3_ca
        option: keyUsage
        value: 'digitalSignature, keyEncipherment'
      - section: CA_default
        option: copy_extensions
        value: copy
  tags:
      - cert

- name: update openssl DNS settings
  become: yes
  ini_file:
      dest: /etc/ssl/openssl.cnf
      section: alternate_names
      option: 'DNS.{{ item.0 }}'
      value: '{{ item.1.hostname }}'
  with_indexed_items: "{{ hosts }}"
  tags:
      - cert

# h/t to https://serialized.net/2013/04/simply-generating-self-signed-ssl-certs-with-ansible/
- name: create self-signed SSL cert
  become: yes
  command: openssl req -new -nodes -x509 -subj "/C=US/ST=Virginia/L=Richmond/O=Foster Made/CN=Local Dev" -days 3650 -keyout /etc/ssl/private/ssl.key -out /etc/ssl/certs/ssl.crt -extensions v3_ca
  args:
      creates: /etc/ssl/certs/ssl.crt
  notify:
        - restart apache
  tags:
      - cert