---
- name: create openssl conf file
  become: yes
  template:
      src: openssl.cnf.j2
      dest: /usr/local/lib/openssl.cnf
  notify:
      - restart apache
  tags:
      - cert

# h/t to https://serialized.net/2013/04/simply-generating-self-signed-ssl-certs-with-ansible/
- name: create self-signed SSL cert
  become: yes
  command: openssl req -new -nodes -x509 -subj "/C=US/ST=Virginia/L=Richmond/O=Foster Made/CN=Local Dev" -days 3650 -keyout /etc/ssl/private/{{ hostname }}.key -out /etc/ssl/certs/{{ hostname }}.crt -extensions v3_ca -config /usr/local/lib/openssl.cnf
  args:
      creates: /etc/ssl/certs/{{ hostname }}.crt
  notify:
        - restart apache
  tags:
      - cert
