---
- name: install php
  become: yes
  apt:
      name: "{{ item }}"
      state: present
  with_items: "{{ php_modules | default([]) }}"
  tags:
      - php_modules

- name: ensure php-fpm is started
  become: yes
  service:
      name: "{{ fpm_service }}"
      state: started
      enabled: yes

- name: change php-fpm to listen on socket
  become: yes
  ini_file:
      dest: "{{ fpm_socket }}"
      section: www
      option: listen
      value: 127.0.0.1:9000

- name: set default timezone
  become: yes
  ini_file:
      dest: "{{ fpm_timezone }}"
      section: Date
      option: date.timezone
      value: 'America/New_York'
  notify:
      - restart php
