---
- name: setup xdebug config
  become: yes
  template:
      src: files/ini/20-xdebug.ini
      dest: /etc/php/{{ php_version }}/cli/conf.d/20-xdebug.ini
  notify:
      - restart apache
      - restart php
  tags:
      - xdebug
