---
- name: install php
  become: yes
  apt:
      name: "{{ item }}"
      state: present
  with_items: "{{ ['php5-fpm', 'php5-cli'] + php_modules }}"

- name: ensure php5-fpm is started
  become: yes
  service:
      name: php5-fpm
      state: started
      enabled: yes

- name: change php-fpm to listen on socket
  become: yes
  ini_file:
      dest: /etc/php5/fpm/pool.d/www.conf
      section: www
      option: listen
      value: 127.0.0.1:9000

- name: set default timezone
  become: yes
  ini_file:
      dest: /etc/php5/fpm/php.ini
      section: Date
      option: date.timezone
      value: 'America/New_York'
  notify:
      - restart php
