---
- name: restart postgresql
  become: yes
  service:
      name: postgresql
      state: restarted

- name: restart nginx
  become: yes
  service:
      name: nginx
      state: restarted

- name: restart supervisor
  become: yes
  command: supervisorctl restart all

- name: update supervisor
  become: yes
  command: supervisorctl update