---
- name: install supervisor
  become: yes
  apt:
      name: supervisor
      state: present

- name: ensure supervisor is enabled
  become: yes
  service:
      name: supervisor
      state: started
      enabled: yes
