---
- name: add latest stable mongodb
  become: yes
  shell: 'echo "deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.4.list'
  args:
      creates: /etc/apt/sources.list.d/mongodb-org-3.4.list
  tags:
      - mongo

- name: install mongodb
  become: yes
  apt:
      name: mongodb
      state: present
      update_cache: yes
  tags:
      - mongo

- name: ensure mongo is started
  become: yes
  service:
      name: mongodb
      state: started
      enabled: yes
  tags:
      - mongo
