---
- stat:
      path: /usr/local/bin/dynamodb
  register: dynamodb
  tags:
      - dynamodb

- block:
    - name: install java
      become: yes
      apt:
          name: default-jre
          state: present
      tags:
          - java
          - dynamodb

    - name: get latest dynamodb hash
      get_url:
          url: https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz.sha256
          dest: /tmp/dynamodb_checksum

    - name: register dynamodb checksum
      shell: cut -d' ' -f1 /tmp/dynamodb_checksum
      register: dynamodb_checksum

    - name: remove downloaded hash file
      file:
          path: /tmp/dynamodb_checksum
          state: absent

    - name: download dynamodb archive
      become: yes
      get_url:
          url: https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz
          checksum: sha256:{{ dynamodb_checksum.stdout }}
          dest: /tmp/dynamodb.tar.gz
          mode: 0644

    - name: create dest directory
      file:
          path: /usr/local/lib/dynamodb
          state: directory

    - name: unarchive the downloaded package
      unarchive:
          remote_src: yes
          src: /tmp/dynamodb.tar.gz
          dest: /usr/local/lib/dynamodb

    - name: create supervisor dynamodb program
      become: yes
      template:
          src: ../templates/program_dynamodb.conf.j2
          dest: /etc/supervisor/conf.d/program_dynamodb.conf

    - name: ensure dynamodb is included in supervisorctl
      become: yes
      supervisorctl:
          name: dynamodb
          state: present

  become: yes
  when: dynamodb.stat.exists == false
  tags:
      - dynamodb
