---
- name: restart apache
  become: yes
  service:
      name: apache2
      state: restarted

- name: restart mysql
  become: yes
  service:
      name: mysql
      state: restarted

- name: restart php
  become: yes
  service:
      name: "{{ fpm_service }}"
      state: restarted
