---
- name: install nginx
  become: yes
  apt: 
      name: nginx
      update_cache: yes
      state: installed

- name: ensure nginx service is started
  become: yes
  service: 
      name: nginx 
      state: started 
      enabled: yes

- name: disable default nginx site
  become: yes
  file:
      path: /etc/nginx/sites-enabled/default
      state: absent

- name: create virtual host file
  become: yes
  template:
      src: nginx-vhost.conf.j2
      dest: /etc/nginx/sites-available/{{ item.hostname }}
  with_items: "{{ hosts }}"
  notify:
      - restart nginx
  tags:
      - vhost

- name: enable new site
  become: yes
  file:
      src: /etc/nginx/sites-available/{{ item.hostname }}
      dest: /etc/nginx/sites-enabled/{{ item.hostname }}
      state: link
  with_items: "{{ hosts }}"
  notify:
      - restart nginx