---
- name: install pip requirements in virtualenv
  pip:
      virtualenv: "{{ item.web_root }}"
      requirements: "{{ item.web_root }}/requirements.txt"
  with_items: "{{ hosts }}"
  
- name: migrate database
  django_manage:
      command: migrate
      app_path: "{{ item.document_root }}"
      virtualenv: "{{ item.web_root }}"
  with_items: "{{ hosts }}"

- name: add STATIC_ROOT to settings.py
  lineinfile:
      path: "{{ item.web_root}}/{{ item.project_name }}/settings.py"
      line: "STATIC_ROOT = os.path.join(BASE_DIR, 'static/')"
  with_items: "{{ hosts }}"

- name: collect static
  django_manage:
      command: collectstatic
      app_path: "{{ item.document_root }}"
      virtualenv: "{{ item.web_root }}"
  with_items: "{{ hosts }}"
  notify:
      - update supervisor
      - restart supervisor
