---
- name: install pip requirements in virtualenv
  pip:
      virtualenv: "{{ item.web_root }}"
      requirements: "{{ item.web_root }}/requirements.txt"
  with_items: "{{ hosts }}"
  
- name: migrate database
  django_manage:
      command: migrate
      app_path: "{{ item.document_root }}"
      virtualenv: "{{ item.web_root }}"
  with_items: "{{ hosts }}"

- name: collect static
  django_manage:
      command: collectstatic
      app_path: "{{ item.document_root }}"
      virtualenv: "{{ item.web_root }}"
  with_items: "{{ hosts }}"
  notify:
      - update supervisor
      - restart supervisor